<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <link rel="stylesheet" href="<?= $base_url ?>/assets/css/style.css">
</head>
<body>
  <div class="container">
    <h2>AI Graded Quiz</h2>

    <form method="POST" action="<?= $base_url ?>/quiz/submit">
      <p><strong>Question:</strong> What is photosynthesis?</p>
      <textarea name="student_answer" rows="5" required></textarea><br><br>
      <button type="submit">Submit</button>
    </form>

    <?php if (!empty($grading)): ?>
      <div class="result">
        <h3>AI Grading Feedback</h3>
        <p><strong><?= nl2br(htmlspecialchars($grading)) ?></strong></p>
      </div>
    <?php endif; ?>

    <?php if (!empty($recommendation)): ?>
      <div class="result">
        <h3>Study Recommendation</h3>
        <p><?= nl2br(htmlspecialchars($recommendation)) ?></p>
      </div>
    <?php endif; ?>

    <p class="disclaimer">(This feedback is generated by an AI model and may not be 100% accurate.)</p>
    <br><a href="<?= $base_url ?>/role">← Back to Role Selection</a>

    <form method="POST" action="<?= $base_url ?>/role/logout" style="margin-top: 20px;">
        <button type="submit">Logout</button>
    </form>
  </div>
</body>
</html>

